spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tdd_course
    driver-class-name: org.postgresql.Driver
    username: tdd_course
    password: tdd_course
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
